### ISSUE TITLE
Bad spell rules value in spell 1085

### ISSUE THREAD

**Issue by DudeMcDude** [Sagenlicht/ToEE_Mods#2]
https://github.com/Sagenlicht/ToEE_Mods/blob/b4bb0d219f6887c098d68aec5a1ad6c9200675bc/overrides/rules/spells/1085%20-%20Fell%20the%20Greatest%20Foe.txt#L9

There is no value "No", it should be "none". This is slightly buggy in the sense that it'll actually assign fortitude save, but then again you usually trigger the saving throw manually so it's moot.

**Comment by DudeMcDude** [comment]
Oh and it looks like a bunch more spells have that issue too, including 1088, 1096...
I'll improve the logging so it alerts about the spell.

Edit: also went ahead and added support for "No" because why not I guess.

**Comment by Sagenlicht** [comment]
I will fix this, that's  my bad. It's nice that you try to catch my errors in the engine, but I think, I should do the rules files correctly :)

Will run a script locally to filter this

**Comment by Sagenlicht** [comment]
> Oh and it looks like a bunch more spells have that issue too, including 1088, 1096...
> I'll improve the logging so it alerts about the spell.
> 
> Edit: also went ahead and added support for "No" because why not I guess.

Fixed spells:
spells\1085 - Fell the Greatest Foe.txt
spells\1088 - Veil of Shadow.txt
spells\1096 - Allegro.txt
spells\1127 - Cloak of Bravery.txt
spells\1129 - Quick March.txt

That should be all Saving Throw: No errors
